name: Generate Tweet Statistics

# Trigger on push to the main branch and changes in the tweets directory
on:
  push:
    branches:
      - main
    paths:
      - 'tweets/**'

jobs:
  generate_statistics:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Run the statistics script
      - name: Run generate_statistics.py script
        run: python .github/scripts/generate_statistics.py

      # Append statistics to README.md
      - name: Append statistics to README
        run: |
          cat statistics_output.txt >> README.md

      # Commit and push changes to README.md
      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add README.md
          git commit -m "Update README with tweet statistics"
          git push